name: Run Technodrom Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  test:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: technodrom
      - name: Install Playwright Browsers
        run: npx playwright install chromium
        working-directory: technodrom
      - name: Run Playwright tests
        run: npx playwright test
        env:
          ENDPOINT_FOR_REPORT: ${{ secrets.ENDPOINT_FOR_REPORT }}
          MAILSAC_API_KEY: ${{ secrets.MAILSAC_API_KEY }}
          STORE_NAME_FOR_DELIVERY_OPTION: ${{ secrets.STORE_NAME_FOR_DELIVERY_OPTION }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_NAME: ${{ secrets.TEST_NAME }}
          TEST_PHONE_NUMBER: ${{ secrets.TEST_PHONE_NUMBER }}
        working-directory: technodrom
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: technodrom-playwright-report
          path: technodrom/playwright-report/
          retention-days: 30
